<a href="https://colab.research.google.com/github/mnairobi/-basic-calculator/blob/master/Nicholus_Kiriinya_SC212_0598_2022.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Step 4.1: K-Nearest Neighbors (KNN) Classification



In [ ]:
#Import libraries
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.datasets import load_iris
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report


In [ ]:
#Load Iris dataset
iris = load_iris()
x = iris.data
y= iris.target

In [ ]:
#Split the dataset (Training & Testing)
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=42)

In [ ]:
#Create and train the KNN model
knn=KNeighborsClassifier(n_neighbors=5)
knn.fit(x_train,y_train)

KNeighborsClassifier()

In [ ]:
#Make predictions
y_pred=knn.predict(x_test)

In [ ]:
y_pred[:5]


array([1, 0, 2, 1, 1])

In [ ]:
#Evaluate the model
#Accuracy
accuracy=accuracy_score(y_test,y_pred)
print("accuracy",accuracy)

accuracy 1.0


In [ ]:
#Confusion Matrix
print("Confusion Matrix")
print(confusion_matrix(y_test,y_pred))

Confusion Matrix
[[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]


In [ ]:
#Classification Report
print("Classification Report")
print(classification_report(y_test,y_pred,target_names=iris.target_names))

Classification Report
              precision    recall  f1-score   support

      setosa       1.00      1.00      1.00        10
  versicolor       1.00      1.00      1.00         9
   virginica       1.00      1.00      1.00        11

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30



Step 4.2: Naive Bayes Classification (Gaussian Naive Bayes)

In [ ]:
#Import Naive Bayes
from sklearn.naive_bayes import GaussianNB

In [ ]:
#Create and train the Naive Bayes model
nb=GaussianNB()
nb.fit(x_train,y_train)

GaussianNB()

In [ ]:
#Make predictions
y_pred_nb=nb.predict(x_test)

In [ ]:
#Evaluate the Model
#Accuracy
accuracy_nb = accuracy_score(y_test,y_pred_nb)
print("accuracy",accuracy_nb)

accuracy 1.0


In [ ]:
#Confusion Matrix
print("Confusion Matrix")
print(confusion_matrix(y_test,y_pred_nb))

Confusion Matrix
[[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]


In [ ]:
#Classification Report
print("Classification Report")
print(classification_report(y_test,y_pred_nb,target_names=iris.target_names))

Classification Report
              precision    recall  f1-score   support

      setosa       1.00      1.00      1.00        10
  versicolor       1.00      1.00      1.00         9
   virginica       1.00      1.00      1.00        11

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30



Step 4.3: Support Vector Machine (SVM)

In [ ]:
#Import SVM
from sklearn.svm import SVC


In [ ]:
#Train the SVM model
svm = SVC(kernel='rbf', C=1.0, gamma='scale')
svm.fit(x_train, y_train)


SVC()

In [ ]:
#Make predictions
y_pred_svm = svm.predict(x_test)


In [ ]:
#Evaluate the SVM
#Accuracy
accuracy_svm = accuracy_score(y_test, y_pred_svm)
print("Accuracy:", accuracy_svm)


Accuracy: 1.0


In [ ]:
#Confusion Matrix
print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred_svm))



Confusion Matrix:
[[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]


In [ ]:
#Classification Report
print("Classification Report:")
print(classification_report(y_test, y_pred_svm, target_names=iris.target_names))


Classification Report:
              precision    recall  f1-score   support

      setosa       1.00      1.00      1.00        10
  versicolor       1.00      1.00      1.00         9
   virginica       1.00      1.00      1.00        11

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30



Step 4.4: Decision Tree Classification

In [ ]:
#Import Decision Tree
from sklearn.tree import DecisionTreeClassifier


In [ ]:
#Train the Decision Tree
dt = DecisionTreeClassifier(
    criterion='gini',
    max_depth=None,
    random_state=42
)
dt.fit(x_train, y_train)


DecisionTreeClassifier(random_state=42)

In [ ]:
#Make Predictions
y_pred_dt = dt.predict(x_test)


In [ ]:
#Evaluate the Model
#Accuracy
accuracy_dt = accuracy_score(y_test, y_pred_dt)
print("Accuracy:", accuracy_dt)


Accuracy: 1.0


In [ ]:
#Confusion Matrix
print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred_dt))


Confusion Matrix:
[[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]


In [ ]:
#Classification Report
print("Classification Report:")
print(classification_report(y_test, y_pred_dt, target_names=iris.target_names))


Classification Report:
              precision    recall  f1-score   support

      setosa       1.00      1.00      1.00        10
  versicolor       1.00      1.00      1.00         9
   virginica       1.00      1.00      1.00        11

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30



Step 4.5: Random Forest Classification

In [ ]:
#Import Random Forest
from sklearn.ensemble import RandomForestClassifier


In [ ]:
#Train the Random Forest
rf = RandomForestClassifier(
    n_estimators=100,
    criterion='gini',
    random_state=42
)

rf.fit(x_train, y_train)


RandomForestClassifier(random_state=42)

In [ ]:
#Make Predictions
y_pred_rf = rf.predict(x_test)


In [ ]:
#Evaluate the Random Forest
#Accuracy
accuracy_rf = accuracy_score(y_test, y_pred_rf)
print("Accuracy:", accuracy_rf)


Accuracy: 1.0


In [ ]:
#Confusion Matrix
print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred_rf))


Confusion Matrix:
[[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]


In [ ]:
#Classification Report
print("Classification Report:")
print(classification_report(y_test, y_pred_rf, target_names=iris.target_names))


Classification Report:
              precision    recall  f1-score   support

      setosa       1.00      1.00      1.00        10
  versicolor       1.00      1.00      1.00         9
   virginica       1.00      1.00      1.00        11

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30



Step 5: Regression Algorithms

Dataset: California Housing

In [ ]:
#Import Required Libraries
import numpy as np

from sklearn.datasets import fetch_california_housing
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import PolynomialFeatures
from sklearn.linear_model import LinearRegression, Lasso, Ridge
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score


In [ ]:
# Load dataset
housing = fetch_california_housing()
X = housing.data
y = housing.target

# Train-test split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)


In [ ]:
def evaluate_regression(y_true, y_pred):
    mae = mean_absolute_error(y_true, y_pred)
    mse = mean_squared_error(y_true, y_pred)
    rmse = np.sqrt(mse)
    r2 = r2_score(y_true, y_pred)

    return mae, mse, rmse, r2


5.1 Linear Regression,
Train

In [ ]:
lr = LinearRegression()
lr.fit(X_train, y_train)


LinearRegression()

In [ ]:
#Predict
y_pred_lr = lr.predict(X_test)


In [ ]:
#Evaluate
mae_lr, mse_lr, rmse_lr, r2_lr = evaluate_regression(y_test, y_pred_lr)

print("Linear Regression")
print("MAE:", mae_lr)
print("MSE:", mse_lr)
print("RMSE:", rmse_lr)
print("R²:", r2_lr)


Linear Regression
MAE: 0.533200130495698
MSE: 0.5558915986952422
RMSE: 0.7455813830127749
R²: 0.5757877060324524


5.2 Polynomial Regression

In [ ]:
#Transform Features
poly = PolynomialFeatures(degree=2, include_bias=False)

X_train_poly = poly.fit_transform(X_train)
X_test_poly = poly.transform(X_test)


In [ ]:
#Train
poly_reg = LinearRegression()
poly_reg.fit(X_train_poly, y_train)


LinearRegression()

In [ ]:
#Predict
y_pred_poly = poly_reg.predict(X_test_poly)


In [ ]:
#Evaluate
mae_poly, mse_poly, rmse_poly, r2_poly = evaluate_regression(y_test, y_pred_poly)

print("Polynomial Regression")
print("MAE:", mae_poly)
print("MSE:", mse_poly)
print("RMSE:", rmse_poly)
print("R²:", r2_poly)


Polynomial Regression
MAE: 0.4670009334741879
MSE: 0.4643015240584696
RMSE: 0.6813967449720241
R²: 0.6456819727519338


5.3 Lasso Regression (L1 Regularisation)

In [ ]:
#Train
lasso = Lasso(alpha=0.1, max_iter=10000)
lasso.fit(X_train, y_train)


Lasso(alpha=0.1, max_iter=10000)

In [ ]:
#Predict
y_pred_lasso = lasso.predict(X_test)


In [ ]:
#Evaluate
mae_lasso, mse_lasso, rmse_lasso, r2_lasso = evaluate_regression(y_test, y_pred_lasso)

print("Lasso Regression")
print("MAE:", mae_lasso)
print("MSE:", mse_lasso)
print("RMSE:", rmse_lasso)
print("R²:", r2_lasso)


Lasso Regression
MAE: 0.5816074623949868
MSE: 0.6135115198058131
RMSE: 0.7832697618354822
R²: 0.5318167610318159


5.4 Ridge Regression (L2 Regularisation)

In [ ]:
#Train
ridge = Ridge(alpha=1.0)
ridge.fit(X_train, y_train)


Ridge()

In [ ]:
#Predict
y_pred_ridge = ridge.predict(X_test)


In [ ]:
#Evaluate
mae_ridge, mse_ridge, rmse_ridge, r2_ridge = evaluate_regression(y_test, y_pred_ridge)

print("Ridge Regression")
print("MAE:", mae_ridge)
print("MSE:", mae_ridge)
print("RMSE:", rmse_ridge)
print("R²:", r2_ridge)


Ridge Regression
MAE: 0.5332039182571584
MSE: 0.5332039182571584
RMSE: 0.7455222779992692
R²: 0.5758549611440138
